name: Scan with Detekt

on:
  push:
    branches: [ main ]
    paths-ignore:
      - ".github/**"
      - "**.md"
      - ".gitignore"
      - ".editorconfig"
  pull_request:
    branches: [ main ]
    paths-ignore:
      - ".github/**"
      - "**.md"
      - ".gitignore"
      - ".editorconfig"
    
jobs:
  scan:
    name: Scan
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - name: Setup Detekt
      uses: peter-murray/setup-detekt@v1
      with:
        detekt_version: 1.15.0
    - name: Run Detekt
      continue-on-error: true
      run: |
        detekt --input ${{ github.workspace }} --report sarif:${{ github.workspace }}/detekt.sarif.json
    - name: Make artifact location URIs relative
      continue-on-error: true
      run: |
        echo "$(
          jq \
            --arg github_workspace ${{ github.workspace }} \
            '. | ( .runs[].results[].locations[].physicalLocation.artifactLocation.uri |= if test($github_workspace) then .[($github_workspace | length | . + 1):] else . end )' \
            ${{ github.workspace }}/detekt.sarif.json
        )" > ${{ github.workspace }}/detekt.sarif.json
    - uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: ${{ github.workspace }}/detekt.sarif.json
        checkout_path: ${{ github.workspace }}
