name: PR Checker
on:
  pull_request_target:
    types: [ opened ]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  reviewer_assign:
    name: Assign Reviewers
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/auto-assign-action@v1.2.1 # assign reviewer
        name: Assign Reviewers
        with:
          configuration-path: ".github/pr_review.yml"
  title_check:
    name: Check Title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v3.4.0
        name: Check Title
        with:
          types: |
            feat
            feature
            fix
            bugfix
            deps
            build
            chore
            perf
            refactor
          scopes: |
            ci
            gradle
            api
            engine/discord
            engine/twitch
            module/youtube
            engine/*
            module/*
          requiredScope: true
          subjectPatternError: |
            Thank you for your contribiution. Unfortunate your title doesn't contain a proper title format.
            The title must be: `<type>(<scope>): {title}`, when [`type`](https://twitch4j.github.io/docs/contributing/pull-request-guide#supported-types)
            and [`scope`](https://twitch4j.github.io/docs/contributing/pull-request-guide#supported-scopes) **MUST** be defined in the sample title.
            For more details about sending pull request, please refer to our [documentation](https://twitch4j.github.io/docs/contributing/pull-request-guide)
