name: Release
on:
  workflow_dispatch:
    inputs:
      release_notes:
        description: Release Notes
        required: true

env:
  CI: true
  GPG_KEY: ${{ secrets.GPG_KEY }}
  GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  SLACK_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}/slack
  DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          ref: main
      - uses: actions/cache@v2.1.4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: JDK8-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: JDK8-gradle-
      - uses: actions/setup-java@v1.4.3
        with:
          java-version: 8
      - uses: actions/setup-node@v2.1.5
      - run: |
          chmod +x ./gradlew
          ./gradlew check
      - uses: cycjimmy/semantic-release-action@v2.5.3
        env:
          RELEASE_NOTES: ${{ github.event.inputs.release_notes }}
        with:
          extra_plugins: |
            gradle-semantic-release-plugin
            @semantic-release/git
