name: Release
on: [ workflow_dispatch ]

env:
  RELEASE: true
  GPG_KEY: ${{ secrets.GPG_KEY }}
  GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
        name: Checkout
        with:
          ref: main
      - uses: actions/cache@v2.1.4
        name: Gradle Cache JDK8
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: JDK8-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: JDK8-gradle-
      - uses: actions/setup-java@v2.3.1
        name: Setup JDK8
        with:
          java-version: 8
      - uses: actions/setup-node@v2.1.5
        name: Setup NodeJS
      - name: Pre-Release Test
        run: |
          chmod +x ./gradlew
          ./gradlew check
      - uses: cycjimmy/semantic-release-action@v2.5.3
        name: Release
        with:
          branch: main
          extra_plugins: |
            gradle-semantic-release-plugin
            @semantic-release/git
            conventional-changelog-conventionalcommits
