name: Release
on:
  workflow_dispatch:
    inputs:
      release_notes:
        description: Release Notes
        required: true

env:
  RELEASE: true
  GPG_KEY: ${{ secrets.GPG_KEY }}
  GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          ref: main
      - uses: actions/cache@v2.1.4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: JDK8-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: JDK8-gradle-
      - uses: actions/setup-java@v1.4.3
        with:
          java-version: 8
      - uses: actions/setup-node@v2.1.5
      - run: |
          chmod +x ./gradlew
          ./gradlew check
      - uses: actions/github-script@v3.1.1
        id: user
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const result await github.users.getByUsername({ username: context.actor });
            return result;
      - uses: cycjimmy/semantic-release-action@v2.5.3
        env:
          GIT_AUTHOR_NAME: ${{ steps.user.outputs.result.login }}
          GIT_AUTHOR_EMAIL: ${{ steps.user.outputs.result.email }}
          GIT_COMMITTER_NAME: ${{ steps.user.outputs.result.login }}
          GIT_COMMITTER_EMAIL: ${{ steps.user.outputs.result.email }}
          RELEASE_NOTES: ${{ github.event.inputs.release_notes }}
        with:
          extra_plugins: |
            gradle-semantic-release-plugin
            @semantic-release/git
